base_url: https://www.cnn.com/

sections:
  US:
    url: https://www.cnn.com/us
    attrs:
      data-editable: "headline"
  World:
    url: https://www.cnn.com/world
    attrs:
      data-editable: "headline"
