base_url: https://www.bbc.com/

sections:
  attrs:
    class: "gs-c-promo-heading__title"

categories:
  news:
    world:
        us_and_canada: null
    world-60525350: null #war in ukraine
    science-environment-56837908: null #climate
    uk: null
    business: null
    technology: null
    entertainment_and_arts: null
    health: null

aliases:
  ukraine_war: world-60525350
  climate: science-environment-56837908
  tech: technology
  entertainment: entertainment_and_arts
  arts: entertainment_and_arts
  science: science_and_environment

article:
  attrs:
    data-component: "text-block"
