base_url: https://www.bbc.com/

sections:
  attrs:
    class: "gs-c-promo-heading__title"

categories:
  news:
    world: null
    us_and_canada: null
    uk: null
    business: null
    tech: null

article:
  attrs:
    data-component: "text-block"
